### ISSUE TITLE
Folder name "aux" causes problems on Windows 

### ISSUE THREAD

**Issue by linchaobao** [jponttuset/davis-matlab#11]
Hi Guys,

Is it possible to rename the folder name "aux" to another name instead? It causes some problem on Windows OS during git operation. Thanks a lot! 

There is similar problem found in other repo, see here for an example: https://github.com/swcarpentry/DEPRECATED-bc/pull/464/files

**Comment by jponttuset** [comment]
Done, let me know if it does not work yet
