### ISSUE TITLE
Code compatible issue for Windows MSVC

### ISSUE THREAD

**Issue by linchaobao** [jponttuset/davis-matlab#12]
Hi Guys, 

In order to get compiled on Windows using Visual Studio 2015 for the logical keyword "or" (C++11 feature), a header file `iso646.h` should be included in the cpp files in folder `third-party/polycont/matlab/private`. Would you please consider to add the following code in the cpp files in the above folder: 

```
#ifdef _MSC_VER
	#include <iso646.h>
#endif
```

This will fix the compiling error as follows (copied here in case other guys would see this error): 

```
polycont\cpp/in_out_sort.hpp(55): error C2146: syntax error: missing ')' before identifier 'or'
polycont\cpp/in_out_sort.hpp(55): error C2065: 'or': undeclared identifier
polycont\cpp/in_out_sort.hpp(55): error C2146: syntax error: missing ';' before identifier 'p'
polycont\cpp/in_out_sort.hpp(55): error C2059: syntax error: ')'
polycont\cpp/in_out_sort.hpp(56): error C2146: syntax error: missing ';' before identifier 'p'
```

**Comment by jponttuset** [comment]
Hi @linchaobao,

Thanks for pointing this out and suggesting the fix. Could you please check that it works now?
I don't have access to a Windows computer...

Best,

**Comment by linchaobao** [comment]
Hi @jponttuset , 

Thanks for the quick response. Almost done, except that in `mask2poly_mex.cpp` I had to include the `matlab_interface.hpp` before `mask2polycont.hpp` to work. So the begining in `mask2poly_mex.cpp` looks like 

```
#include "mex.h"
#include <Eigen/Dense>
#include <matlab/private/matlab_interface.hpp>
#include <cpp/mask2polycont.hpp>
```

Best,

**Comment by jponttuset** [comment]
Thanks again @linchaobao!
Let's see if now we fixed it for good :)

**Comment by linchaobao** [comment]
Seems perfect for me :-)

**Comment by jponttuset** [comment]
Cool, thanks!
