### ISSUE TITLE
Implement three measures

### ISSUE THREAD

**Issue by InstantWindy** [jponttuset/davis-matlab#15]
Hello, thank you for sharing your code.But I have a question about the official code "jaccard_region.m" file and the "f_boundary.m" file.But I don't know what the input parameters of the "f_boundary " function of the'jaccard_region.m'file and 'jaccard_region' function of the 'f_boundary.m' file should be? Thank you!

**Comment by scaelles** [comment]
For the evaluation, we use the default parameters of the functions and you only have to provide the ground truth and your output mask. I would strongly recommend not using the functions individually and using the scripts to evaluate your method suggested in [here](https://github.com/davisvideochallenge/davis-matlab#evaluate-your-technique).
