### ISSUE TITLE
Davis annotation 

### ISSUE THREAD

**Issue by InstantWindy** [jponttuset/davis-matlab#16]
Hi, In the Davis 2017 dataset, some different categories have the same label color， for example, the label color of bear is the same as that of the bicycle. But segmentation requires different classes with different colors, so if so, what should I do with tagging Davis 2017 data sets?
Thank you!

**Comment by scaelles** [comment]
The pixel ids in each mask are not related with any category. The ids go from 1 to the number of objects of that specific sequence.

The semi-supervised video object segmentation task is not category dependent as the methods are supposed to segment any type of object given by the mask in the first frame.

**Comment by scaelles** [comment]
As a side note and not related with the video object segmentation task, we released the category for all the objects in Davis 2017 [here](https://davischallenge.org/davis2017/code.html) in the "Object categories" section. The masks that you can download there have the pixel id category dependent so they have the format that you were expecting.
