### ISSUE TITLE
build error, fatal error C1083 cannot open include file

### ISSUE THREAD

**Issue by innerLocus** [jponttuset/davis-matlab#4]
HI 
I am tring to test but have some issue below. 

MEX가 성공적으로 완료되었습니다.
'Microsoft Visual C++ 2013 Professional'(으)로 빌드됩니다.
다음 사용 중 오류가 발생함: mex
mask2poly_mex.cpp
polycont\cpp/simplify.hpp(31) : warning C4244: 'argument' : conversion from 'ClipperLib::cInt' to 'const double', possible loss of data
polycont\cpp/simplify.hpp(32) : warning C4244: 'argument' : conversion from 'ClipperLib::cInt' to 'const double', possible loss of data
polycont\cpp/simplify.hpp(50) : warning C4244: 'argument' : conversion from 'double' to 'ClipperLib::cInt', possible loss of data
polycont\cpp/in_out_sort.hpp(55) : error C2146: syntax error : missing ')' before identifier 'or'
polycont\cpp/in_out_sort.hpp(55) : error C2065: 'or' : undeclared identifier
polycont\cpp/in_out_sort.hpp(55) : error C2146: syntax error : missing ';' before identifier 'p'
polycont\cpp/in_out_sort.hpp(55) : error C2059: syntax error : ')'
polycont\cpp/in_out_sort.hpp(56) : error C2146: syntax error : missing ';' before identifier 'p'
polycont\cpp/in_out_sort.hpp(56) : warning C4553: '==' : operator has no effect; did you intend '='?
polycont\cpp/in_out_sort.hpp(59) : error C2146: syntax error : missing ')' before identifier 'or'
polycont\cpp/in_out_sort.hpp(59) : error C2059: syntax error : ')'
polycont\cpp/in_out_sort.hpp(69) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
polycont\cpp/in_out_sort.hpp(73) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
polycont\cpp/in_out_sort.hpp(83) : warning C4018: '<' : signed/unsigned mismatch
polycont\cpp/in_out_sort.hpp(117) : error C2065: 'not' : undeclared identifier
polycont\cpp/in_out_sort.hpp(117) : error C2146: syntax error : missing ')' before identifier 'children_in_it'
polycont\cpp/in_out_sort.hpp(117) : error C2059: syntax error : ')'
polycont\cpp/in_out_sort.hpp(121) : error C2143: syntax error : missing '}' before ';'
polycont\cpp/in_out_sort.hpp(121) : error C2064: term does not evaluate to a function taking 1 arguments
polycont\cpp/in_out_sort.hpp(128) : error C2181: illegal else without matching if
polycont\cpp/in_out_sort.hpp(142) : error C2065: 'MatrixType' : undeclared identifier
polycont\cpp/in_out_sort.hpp(142) : error C2923: 'std::vector' : 'MatrixType' is not a valid template type argument for parameter '_Ty'
polycont\cpp/in_out_sort.hpp(144) : error C2065: 'cont_inc' : undeclared identifier
polycont\cpp/in_out_sort.hpp(144) : error C2146: syntax error : missing ';' before identifier 'inc'
polycont\cpp/in_out_sort.hpp(144) : error C2065: 'inc' : undeclared identifier
polycont\cpp/in_out_sort.hpp(147) : error C2662: 'bool std::vector<_Ty,_Alloc>::empty(void) throw() const' : cannot convert 'this' pointer
from 'const std::vector' to 'const std::vector<_Ty,_Alloc> &'
        Reason: cannot convert from 'const std::vector' to 'const std::vector<_Ty,_Alloc>'
        Conversion requires a second user-defined-conversion operator or constructor
polycont\cpp/in_out_sort.hpp(151) : error C2065: 'inc' : undeclared identifier
polycont\cpp/in_out_sort.hpp(151) : error C2228: left of '.all_parents' must have class/struct/union
        type is 'unknown-type'
polycont\cpp/in_out_sort.hpp(151) : error C2228: left of '.push_back' must have class/struct/union
polycont\cpp/in_out_sort.hpp(152) : error C2065: 'inc' : undeclared identifier
polycont\cpp/in_out_sort.hpp(152) : error C2228: left of '.all_children' must have class/struct/union
        type is 'unknown-type'
polycont\cpp/in_out_sort.hpp(152) : error C2228: left of '.push_back' must have class/struct/union
polycont\cpp/in_out_sort.hpp(155) : error C2662:
'_Vector_alloc<!std::is_empty<_Alloc_types::_Alloc>::value,std::_Vec_base_types<_Ty,_Alloc_types::_Alloc>>::size_type
std::vector<_Ty,_Alloc>::size(void) throw() const' : cannot convert 'this' pointer from 'const std::vector' to 'const
std::vector<_Ty,_Alloc> &'
        Reason: cannot convert from 'const std::vector' to 'const std::vector<_Ty,_Alloc>'
        Conversion requires a second user-defined-conversion operator or constructor
polycont\cpp/in_out_sort.hpp(156) : error C2065: 'inc' : undeclared identifier
polycont\cpp/in_out_sort.hpp(156) : error C3861: 'add_one_inout': identifier not found
polycont\cpp/in_out_sort.hpp(159) : error C2065: 'inc' : undeclared identifier
polycont\cpp/in_out_sort.hpp(159) : error C3861: 'flatten_hierarchy': identifier not found
polycont\cpp/in_out_sort.hpp(162) : error C2065: 'inc' : undeclared identifier
polycont\cpp/in_out_sort.hpp(162) : error C2228: left of '.all_parents' must have class/struct/union
        type is 'unknown-type'
polycont\cpp/in_out_sort.hpp(162) : error C2228: left of '.erase' must have class/struct/union
polycont\cpp/in_out_sort.hpp(162) : error C2228: left of '.begin' must have class/struct/union
polycont\cpp/in_out_sort.hpp(163) : error C2065: 'inc' : undeclared identifier
polycont\cpp/in_out_sort.hpp(163) : error C2228: left of '.all_children' must have class/struct/union
        type is 'unknown-type'
polycont\cpp/in_out_sort.hpp(163) : error C2228: left of '.erase' must have class/struct/union
polycont\cpp/in_out_sort.hpp(163) : error C2228: left of '.begin' must have class/struct/union
polycont\cpp/in_out_sort.hpp(182) : error C2065: 'inc' : undeclared identifier
polycont\cpp/in_out_sort.hpp(182) : error C2228: left of '.all_parents' must have class/struct/union
        type is 'unknown-type'
polycont\cpp/in_out_sort.hpp(182) : error C2228: left of '.size' must have class/struct/union
polycont\cpp/in_out_sort.hpp(183) : error C2065: 'inc' : undeclared identifier
polycont\cpp/in_out_sort.hpp(183) : error C2228: left of '.all_parents' must have class/struct/union
        type is 'unknown-type'
polycont\cpp/in_out_sort.hpp(183) : error C2228: left of '.size' must have class/struct/union
polycont\cpp/in_out_sort.hpp(184) : error C2065: 'inc' : undeclared identifier
polycont\cpp/in_out_sort.hpp(184) : error C2228: left of '.all_parents' must have class/struct/union
        type is 'unknown-type'
polycont\cpp/in_out_sort.hpp(189) : error C2059: syntax error : '}'
polycont\cpp/in_out_sort.hpp(189) : error C2143: syntax error : missing ';' before '}'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\xhash(18) : error C2143: syntax error : missing ';' before '{'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\xhash(18) : error C2447: '{' : missing function header (old-style formal
list?)
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\xhash(127) : error C2039: 'hash_compare' : is not a member of 'stdext'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\xhash(127) : error C2873: 'hash_compare' : symbol cannot be used in a
using-declaration
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\xhash(128) : error C2039: 'hash_value' : is not a member of 'stdext'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\xhash(128) : error C2873: 'hash_value' : symbol cannot be used in a
using-declaration
polycont\cpp/lines2jordan.hpp(48) : warning C4267: 'return' : conversion from 'size_t' to 'int', possible loss of data
polycont\cpp/lines2jordan.hpp(50) : warning C4267: 'return' : conversion from 'size_t' to 'int', possible loss of data
polycont\cpp/lines2jordan.hpp(142) : warning C4267: 'argument' : conversion from 'size_t' to 'const int', possible loss of data
polycont\cpp/lines2jordan.hpp(144) : warning C4244: 'argument' : conversion from 'double' to 'const int', possible loss of data
polycont\cpp/lines2jordan.hpp(148) : error C2065: 'not' : undeclared identifier
polycont\cpp/lines2jordan.hpp(148) : error C2146: syntax error : missing ')' before identifier 'conts_on_junct'
polycont\cpp/lines2jordan.hpp(148) : error C2059: syntax error : ')'
polycont\cpp/lines2jordan.hpp(160) : error C2144: syntax error : 'std::liststd::pair<int,int,std::allocator<_Ty>>' should be preceded by
'}'
        with
        [
            _Ty=std::pair<int,int>
        ]
polycont\cpp/lines2jordan.hpp(160) : error C2064: term does not evaluate to a function taking 1 arguments
polycont\cpp/lines2jordan.hpp(160) : error C2144: syntax error : 'std::liststd::pair<int,int,std::allocator<_Ty>>' should be preceded by
';'
        with
        [
            _Ty=std::pair<int,int>
        ]
polycont\cpp/lines2jordan.hpp(202) : error C2065: 'not' : undeclared identifier
polycont\cpp/lines2jordan.hpp(202) : error C2146: syntax error : missing ')' before identifier 'swept_junctions'
polycont\cpp/lines2jordan.hpp(202) : error C2059: syntax error : ')'
polycont\cpp/lines2jordan.hpp(205) : error C2143: syntax error : missing '}' before ';'
polycont\cpp/lines2jordan.hpp(205) : error C2064: term does not evaluate to a function taking 1 arguments
polycont\cpp/lines2jordan.hpp(217) : error C2146: syntax error : missing ')' before identifier 'or'
polycont\cpp/lines2jordan.hpp(217) : error C2059: syntax error : ')'
polycont\cpp/lines2jordan.hpp(218) : error C2146: syntax error : missing ';' before identifier 'it_junct'
polycont\cpp/lines2jordan.hpp(217) : error C3861: 'or': identifier not found
polycont\cpp/lines2jordan.hpp(250) : error C2059: syntax error : '}'
polycont\cpp/lines2jordan.hpp(250) : error C2143: syntax error : missing ';' before '}'
polycont\cpp/lines2jordan.hpp(251) : error C2143: syntax error : missing ';' before '}'
polycont\cpp/lines2jordan.hpp(251) : error C2059: syntax error : '}'
polycont\cpp/move2junctions.hpp(16) : error C2143: syntax error : missing ';' before '{'
polycont\cpp/move2junctions.hpp(16) : error C2447: '{' : missing function header (old-style formal list?)
polycont\cpp/clockwise_sort.hpp(36) : error C2065: 'not' : undeclared identifier
polycont\cpp/clockwise_sort.hpp(36) : error C2146: syntax error : missing ')' before identifier 'is_clockwise'
polycont\cpp/clockwise_sort.hpp(36) : error C2059: syntax error : ')'
polycont\cpp/clockwise_sort.hpp(37) : error C2143: syntax error : missing ';' before 'std::reverse'
polycont\cpp/mask2polycont.hpp(54) : warning C4244: '=' : conversion from 'ClipperLib::cInt' to 'double', possible loss of data
polycont\cpp/mask2polycont.hpp(55) : warning C4244: '=' : conversion from 'ClipperLib::cInt' to 'double', possible loss of data
polycont\cpp/mask2polycont.hpp(60) : error C2664: 'std::vector<bool,std::allocator<_Ty>> in_out_check(const std::vector &)' : cannot
convert argument 1 from 'std::vectorPolyCont::MatrixType,std::allocator<_Ty>' to 'const std::vector &'
        with
        [
            _Ty=bool
        ]
        and
        [
            _Ty=PolyCont::MatrixType
        ]
        Reason: cannot convert from 'std::vectorPolyCont::MatrixType,std::allocator<_Ty>' to 'const std::vector'
        with
        [
            _Ty=PolyCont::MatrixType
        ]
        No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
polycont\cpp/mask2polycont.hpp(67) : error C3861: 'move2junctions': identifier not found
polycont\cpp/mask2polycont.hpp(116) : warning C4018: '<' : signed/unsigned mismatch
polycont\cpp/mask2polycont.hpp(118) : warning C4018: '<' : signed/unsigned mismatch
polycont\matlab/private/matlab_interface.hpp(26) : error C2065: 'uint16_t' : undeclared identifier
polycont\matlab/private/matlab_interface.hpp(26) : error C2065: 'im_s_ptr' : undeclared identifier
polycont\matlab/private/matlab_interface.hpp(26) : error C2059: syntax error : ')'
polycont\matlab/private/matlab_interface.hpp(27) : error C2065: 'im_s_ptr' : undeclared identifier
polycont\matlab/private/matlab_interface.hpp(28) : error C2065: 'im_s_ptr' : undeclared identifier
polycont\matlab/private/matlab_interface.hpp(34) : warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
polycont\matlab/private/matlab_interface.hpp(35) : error C2065: 'uint16_t' : undeclared identifier
polycont\matlab/private/matlab_interface.hpp(35) : error C2923: 'Eigen::Array' : 'uint16_t' is not a valid template type argument for
parameter '_Scalar'
polycont\matlab/private/matlab_interface.hpp(35) : error C3203: 'Array' : unspecialized class template can't be used as a template
argument for template parameter 'PlainObjectType', expected a real type
polycont\matlab/private/matlab_interface.hpp(36) : error C2065: 'uint16_t' : undeclared identifier
polycont\matlab/private/matlab_interface.hpp(36) : error C2059: syntax error : ')'
polycont\matlab/private/matlab_interface.hpp(39) : error C2065: 'curr_poly' : undeclared identifier
polycont\matlab/private/matlab_interface.hpp(39) : error C2228: left of '.cols' must have class/struct/union
        type is 'unknown-type'
polycont\matlab/private/matlab_interface.hpp(43) : error C2065: 'curr_poly' : undeclared identifier
polycont\matlab/private/matlab_interface.hpp(43) : error C2228: left of '.rows' must have class/struct/union
        type is 'unknown-type'
polycont\matlab/private/matlab_interface.hpp(46) : error C2065: 'curr_poly' : undeclared identifier
polycont\matlab/private/matlab_interface.hpp(46) : error C2228: left of '.rows' must have class/struct/union
        type is 'unknown-type'
polycont\matlab/private/matlab_interface.hpp(48) : error C3861: 'curr_poly': identifier not found
polycont\matlab/private/matlab_interface.hpp(49) : error C3861: 'curr_poly': identifier not found
polycont\matlab/private/matlab_interface.hpp(70) : error C2065: 'uint16_t' : undeclared identifier
polycont\matlab/private/matlab_interface.hpp(70) : error C2065: 'ptr' : undeclared identifier
polycont\matlab/private/matlab_interface.hpp(70) : fatal error C1003: error count exceeds 100; stopping compilation

오류 발생: matlab_build (line 1)
mex polycont/matlab/private/mask2poly_mex.cpp         clipper/clipper.cpp -Ipolycont -I/opt/local/include -I. -outdir
polycont/matlab/private/

오류 발생: run (line 96)
evalin('caller', [script ';']);

오류 발생: build (line 17)
run matlab_build.m

**Comment by jponttuset** [comment]
Hi innerLocus, the code has never been tested in Windows, in principle it is not supported. I'll try to get a Windows machine to try anyway, but from the errors it seems that your compiler is not supporting the C++11 code, or you have to enforce it with the corresponding flag.

**Comment by jponttuset** [comment]
Hi again, 
The code is now built and tested on Windows, I uploaded the binaries to Github. Please let me know if it works.
Best,

**Comment by jponttuset** [comment]
Closing. Reopen if you still have problems.
